DROP DATABASE IF EXISTS ca;
CREATE DATABASE ca DEFAULT CHARSET=utf8 COLLATE="utf8_general_ci";
USE ca;
	
DROP TABLE IF EXISTS ca_roomlog;
CREATE TABLE ca_roomlog (
    ID INT NOT NULL AUTO_INCREMENT,
	NFC_ID varchar(50),
	room_identifier VARCHAR(50),
	dt DATETIME NOT NULL,
	PRIMARY KEY (ID)
) DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS ca_lesson;
CREATE TABLE ca_lesson (
    ID INT NOT NULL AUTO_INCREMENT,
	begin_time DATETIME NOT NULL,
	end_time DATETIME NOT NULL,
	room_identifier VARCHAR(50),
	topic VARCHAR(150),
	PRIMARY KEY (ID)
) DEFAULT CHARSET=utf8;